### PR TITLE
CustomerPayment

### PR DESCRIPTION
**Pull request by ghtbsokczhh**

### CODE REVIEW

**Comment by Shwetabhk** [comment]
@[ghtbsokczhh](https://github.com/ghtbsokczhh)
The PR is incomplete, we're currently evaluating more and will add details shortly.

You'll also have to add the Type for Customer Payment here for first impressions.
https://github.com/fylein/netsuite-sdk-py/blob/master/netsuitesdk/internal/netsuite_types.py

@[VeNoMouS](https://github.com/VeNoMouS)
Do you have any findings about the type to be added?

**Comment by Sravanksk** [comment]
@ghtbsokczhh 
As stated above, the PR is incomplete, you have to make a bunch of changes in the netsuite_type.py file. You should be adding types related to CustomerPayment under the `ns23` section

You can refer to this schema and add the required types - https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2020_1/schema/record/vendorcredit.html

POST of CustomerPayments is not implemented in your PR, you can refer to this PR https://github.com/fylein/netsuite-sdk-py/commit/617e411c8b42faffe12a24c7f7cc7d6e1e2ddb13

**Comment by ghtbsokczhh** [comment]
sounds good. I will add update soon.

**Comment by ghtbsokczhh** [comment]
What does the netsuite_type.py do? The code currently works for CustomerPayment.get(internalId=xxx) requests with the update.

**Comment by ghtbsokczhh** [comment]
@Sravanksk 

I'm trying to understand what the name space means/does. Why does it need to be in ns23?

**Comment by ghtbsokczhh** [comment]
https://webservices.netsuite.com/xsd/transactions/v2022_1_0/customers.xsd

which namespace should these attributes be added?

**Pull request closed without merging**
