### PR TITLE
Add new types for basic search

### PR DESCRIPTION
**Pull request by mroy-seedbox**

### CODE REVIEW

**Comment by mroy-seedbox** [comment]
Both can be used with `client.basic_search_factory()` & `client.search()`:

`CurrencyRateSearchBasic`:
```
# See https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_2/schema/record/currencyrate.html
client.search(
  client.basic_search_factory(
    'CurrencyRate',
    effectiveDate = getattr(self.conn.client, 'SearchDateField')(
      searchValue = date, # ex: '2022-05-14T12:00:00.000-00:00'
      operator = operator # ex: 'on'
    )
  )
)
```

`ConsolidatedExchangeRateSearchBasic`:
```
# See https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_2/schema/record/consolidatedexchangerate.html
client.search(
  client.basic_search_factory(
    'ConsolidatedExchangeRate',
    periodStartDate = getattr(self.conn.client, 'SearchDateField')(
      searchValue = date, # ex: '2022-04-01T12:00:00.000-00:00'
      operator = 'on'
    ),
    fromSubsidiary = getattr(self.conn.client, 'SearchMultiSelectField')(
      searchValue = from_subsidiary, # ex: { "internalId": 123, "type": "subsidiary" }
      operator = 'anyOf'
    ),
    toSubsidiary = getattr(self.conn.client, 'SearchMultiSelectField')(
      searchValue = to_subsidiary, # ex: { "internalId": 123, "type": "subsidiary" }
      operator = 'anyOf'
    )
  )
)
```

**Comment by mroy-seedbox** [comment]
No rush on this -- for now, I monkey patched it like this:

```
from netsuitesdk.internal.netsuite_types import COMPLEX_TYPES
COMPLEX_TYPES['ns5'].append('CurrencyRateSearchBasic')
COMPLEX_TYPES['ns5'].append('ConsolidatedExchangeRateSearchBasic')
```

**Review by Sravanksk — APPROVED** [review]

**Comment by Sravanksk** [comment]
@mroy-seedbox Thanks for the contribution. We've released this and should be available in `2.12.1`

**Comment by Bazzoo** [comment]
Hello, could you give me an example of how to access the information from a saved search with its id?

**Pull request merged**
