### PR TITLE
Adding more search types

### PR DESCRIPTION
**Pull request by gustahrodrigues**
How to use it?

```python
nc = connect()

transaction_search = nc.client.TransactionSearch(
     basic=nc.client.TransactionSearchBasic(
         type=nc.client.SearchEnumMultiSelectField(
            searchValue=["customerPayment"],
            operator=nc.client.SearchEnumMultiSelectFieldOperator("anyOf"),
         ),
        lastModifiedDate=nc.client.SearchDateField(
            searchValue="2021-07-30T00:07:17.734+0000",
            searchValue2="2021-07-31T11:07:17.734+0000",
            operator=nc.client.SearchDateFieldOperator("within"),
        ),
     )
)
result = nc.client.search(transaction_search)

for r in result.records:
    print(r)

```

### CODE REVIEW

**Comment by gustahrodrigues** [comment]
@Shwetabhk I'm just adding some missing search types

**Comment by Shwetabhk** [comment]
@gustahrodrigues I am merging this, I'll release it by tomorrow

**Comment by Shwetabhk** [comment]
Thanks for the contribution

**Comment by gustahrodrigues** [comment]
@Shwetabhk any news about such a new release? I'm waiting for it to unblock me

**Comment by ashwin1111** [comment]
@gustahrodrigues this is released to PyPi, available in version [2.2.0](https://pypi.org/project/netsuitesdk/2.2.0/)

**Pull request merged**
