### PR TITLE
Adding support for CustomRecord

### PR DESCRIPTION
**Pull request by gustahrodrigues**
- Adding support for `CustomRecordType`
- Changing type of `netsuitesdk/api/custom_records.py` to be `CustomRecord`

### CODE REVIEW

**Comment by gustahrodrigues** [comment]
@ashwin1111 @Shwetabhk @Sravanksk could you please review it?

**Review by Shwetabhk — APPROVED** [review]

**Comment by Shwetabhk** [comment]
@ashwin1111 This will have some implications on our netsuite integration, can you review this

**Comment by Shwetabhk** [comment]
@gustahrodrigues Just give us 1 more day for this one, we'll get back

**Review by ashwin1111 — APPROVED** [review]

**Comment by gustahrodrigues** [comment]
@Shwetabhk could you merge it ?

**Comment by Shwetabhk** [comment]
@gustahrodrigues 
Available in version `2.0.0`
https://github.com/fylein/netsuite-sdk-py/releases/tag/2.0.0

**Pull request merged**
